                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
        location /fadli/ {
                proxy_pass http://127.0.0.1:7000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        # pass PHP scripts to FastCGI server
        #
        #location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php-fpm (or other unix sockets):
        #       fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       fastcgi_pass 127.0.0.1:9000;
        #}
        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
#server {
#       listen 80;
#       listen [::]:80;
#
#       server_name example.com;
#
#       root /var/www/example.com;
#       index index.html;
#
#       location / {
#               try_files $uri $uri/ =404;
#       }
#}
;
cls
clear
nano /etc/nginx/sites-available/default
nginx -t
systemctl restart nginx
systemctl restart nginx
nano /etc/nginx/sites-available/default
systemctl restart nginx
nginx -t
nano /etc/nginx/sites-available/default
cat /etc/nginx/sites-available/default
root@gen4:~# cat /etc/nginx/sites-available/default
##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# https://www.nginx.com/resources/wiki/start/
# https://www.nginx.com/resources/wiki/start/topics/tutorials/config_pitfalls/
# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##
# Default server configuration
#
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;
        root /var/www/html;
        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;
        server_name _;
#       location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                # try_files $uri $uri/ =404;
#               return 404;
#       }
        location /fadli/ {
                proxy_pass http://127.0.0.1:7000/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        # pass PHP scripts to FastCGI server
        #
        #location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php-fpm (or other unix sockets):
        #       fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       fastcgi_pass 127.0.0.1:9000;
        #}
        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}
# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
#server {
#       listen 80;
#       listen [::]:80;
#
#       server_name example.com;
#
#       root /var/www/example.com;
#       index index.html;
#
#       location / {
#               try_files $uri $uri/ =404;
#       }
#}
root@gen4:~#nginx -T | grep fadli -n
nginx -T | grep fadli -n
nano /etc/nginx/sites-available/default
systemctl restart nginx
nginx -t
nano /etc/nginx/sites-available/default
systemctl restart nginx
nginx -t
systemctl restart nginx
cd ../opt/fadli-app-security
ls
gunicorn -w 1 --bind 0.0.0.0:7015 app:app
source venv/bin/activate
gunicorn -w 1 --bind 0.0.0.0:7015 app:app
cd /opt/fardhan-app-security
source venv/bin/activate
nano app.py
python app.py
Last login: Wed Dec 24 14:16:15 2025 from 175.184.235.241
root@gen4:~# cd /opt/fardhan-app-security
root@gen4:/opt/fardhan-app-security# source venv/bin/activate
(venv) root@gen4:/opt/fardhan-app-security# nano app.py
(venv) root@gen4:/opt/fardhan-app-security# python app.py
 * Serving Flask app 'app'
 * Debug mode: on
Address already in use
Port 5000 is in use by another program. Either identify and stop that program, or start the server with a different port.
(venv) root@gen4:/opt/fardhan-app-security#
ss -lntp | grep 5000
kill -9 71234
ss -lntp | grep 5000
python app.py
nano app.py
kill -9 79023
kill -9 78862
ss -lntp | grep 5000
python app.py
app.py
gunicorn --bind 127.0.0.1:8000 app:app
(venv) root@gen4:/opt/fardhan-app-security# gunicorn --bind 127.0.0.1:8000 app:app
[2025-12-24 14:24:21 +0700] [79358] [INFO] Starting gunicorn 23.0.0
[2025-12-24 14:24:21 +0700] [79358] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2025-12-24 14:24:21 +0700] [79358] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2025-12-24 14:24:22 +0700] [79358] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2025-12-24 14:24:22 +0700] [79358] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2025-12-24 14:24:23 +0700] [79358] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2025-12-24 14:24:23 +0700] [79358] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2025-12-24 14:24:24 +0700] [79358] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2025-12-24 14:24:24 +0700] [79358] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2025-12-24 14:24:25 +0700] [79358] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2025-12-24 14:24:25 +0700] [79358] [ERROR] connection to ('127.0.0.1', 8000) failed: [Errno 98] Address already in use
[2025-12-24 14:24:26 +0700] [79358] [ERROR] Can't connect to ('127.0.0.1', 8000)
(venv) root@gen4:/opt/fardhan-app-security#systemctl status fardhan-security
gunicorn --bind 127.0.0.1:8000 app:app
systemctl status fardhan-security
curl http://127.0.0.1:8000
systemctl stop fardhan-security
gunicorn --bind 127.0.0.1:8000 app:app
systemctl start fardhan-security
exit
cd ../
cd/opt/alfan-app-security
cd ../
 cd /opt/alfan-app-securit
cd ../
cd /opt/alfan-app-security
gunicorn --v
pip install gunicorn
apt install -y python3-full python3-venv
python3 -m venv venv
source venv/bin/activate
pip install gunicorn
nano db.py
gunicorn -w 1 --bind 0.0.0.0:8080 app:app
cd /opt/alfan-app-security
apt install -y python3-full python3-venv
python3 -m venv venv
source venv/bin/activate
pip install gunicorn
gunicorn -w 1 --bind 0.0.0.0:5050 app:app 
cd /opt/fardhan-app-security
source venv/bin/activate
python app.py
curl http://127.0.0.1:5000
cd /opt/fardhan-app-security
source venv/bin/activate
python app.py
cd ../
cd /opt/fardhan-app-security
source venv/bin/activate
gunicorn --version
gunicorn -w 3 --bind unix:/run/fardhan-security.sock app:app
rm -f /run/fardhan-security.sock
nano /etc/systemd/system/fardhan-security.service
systemctl daemon-reexec
systemctl daemon-reload
systemctl start fardhan-security
systemctl enable fardhan-security
systemctl status fardhan-security
mysql -u root -p
ss -lntu
ss -lntu
ss -lntu
systemctl nginx status
sudo systemctl status nginx
sudo lsof -i
kill 79998
sudo lsof -i
kill 79550
kill 79551
sudo lsof -i
kill 80175
kill 80176
sudo lsof -i
kill 80291
sudo lsof -i
kill 79406
kill 79737
sudo lsof -i
cd ../opt/fadli-app-security
clear
source venv/bin/activate
gunicorn -w 1 --bind 0.0.0.0:7000 app:app
sudo systemctl daemon-reload
sudo systemctl enable wildaniye-security
sudo systemctl restart wildaniye-security
sudo systemctl status wildaniye-security
cd ../
cd /opt/huda-app-security
ls
source venv/bin/activate
pip install gunicorn
nano db.py
gunicorn -w 1 --bind 0.0.0.0:7009 app:app
nano /etc/nginx/sites-available/bydewa
ln -s /etc/nginx/sites-available/bydewa /etc/nginx/sites-enabled/
nginx -t
systemctl reload nginx
nano /etc/nginx/sites-available/bydewa
cd ../
cd/opt/alfan-app-security
cd ../
cd /opt/alfan-app-security
gunicorn --v
pip install gunicorn
cd /opt/alfan-app-security
apt install -y python3-full python3-venv
python3 -m venv venv
source venv/bin/activate
pip install gunicorn
nano db.py
gunicorn -w 1 --bind 0.0.0.0:5050 app:app
../
cd ../
gunicorn -b 127.0.0.1:5000 app:app
cd /opt/satrio-app-security
which gunicorn
source venv/bin/activate
gunicorn --v
cd ../
ls
cd/opt
ls
cd /opt
ls
cd hakim-app-security 
source venv/bin/activate
source .venv/bin/activate
gunicorn -w 3 --bind 
gunicorn -w 3 --bind 0.0.0.0 app:app
nano db.py
nano db.py
pip install gunicorn
nano db.py
gunicorn -w 1 --bind 0.0.0.0:8004 app:app
cd ../
ls
cd opt ../
cd opt/
ls
opt/yafi-app-security
cd /opt/yafi-app-security
source venv/bin/activate
gunicorn app:app
gunicorn 0.0.0.0:7002 app:app 
gunicorn --bind 0.0.0.0:7002 app:app
cd ../
cd  /opt/iwan-app-security
gunicorn --v
pip install
apt install
pip install gunicorn
apt install python3-xyz
pip install gunicorn
apt install -y python3-venv python3-full
pip install gunicorn
python3 -m venv venv
source venv/bin/activate
pip install gunicorn
nano db.py
gunicorn -w 1 --bind 0.0.0.0:7027 app:app
sudo ss -tulnp
cd ../
ls ../
cd /opt
sudo lsof -i
sudo lsof -i
cd ../
cd /opt/satrio-app-security
source venv/bin/activate
gunicorn -w 1 --bind 0.0.0.0:9999 app:app
sudo apt update && sudo apt upgrade -y
cd /var/www
git clone https://github.com/fardhanmaulana08/LaporPak
cd lapor-pak
cd laporpak
cd LaporPak
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
pip freeze > requirements.txt
pip install -r requirements.txt
export FLASK_APP=app.py
export FLASK_ENV=production
flask run --host=0.0.0.0 --port=5000
export FLASK_APP=app.py
export FLASK_ENV=production
flask run --host=0.0.0.0 --port=5000
pip install gunicorn
gunicorn --bind 0.0.0.0:8000 app:app
sudo lsof -i :8000
sudo kill -9 <PID>
sudo kill -9 1234
(venv) root@gen4:/var/www/LaporPak# sudo lsof -i :8000
COMMAND    PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
gunicorn 80305 root    5u  IPv4 1352401      0t0  TCP localhost:8000 (LISTEN)
gunicorn 80306 root    5u  IPv4 1352401      0t0  TCP localhost:8000 (LISTEN)
gunicorn 80307 root    5u  IPv4 1352401      0t0  TCP localhost:8000 (LISTEN)
gunicorn 80308 root    5u  IPv4 1352401      0t0  TCP localhost:8000 (LISTEN)
(venv) root@gen4:/var/www/LaporPak# sudo kill -9 <PID>
-bash: syntax error near unexpected token `newline'
(venv) root@gen4:/var/www/LaporPak# sudo kill -9 1234
kill: (1234): No such process
(venv) root@gen4:/var/www/LaporPak#gunicorn --bind 0.0.0.0:8000 app:app
gunicorn --bind 0.0.0.0:8000 app:app

ssh username@IP_VPS
sudo apt update && sudo apt upgrade -y
cd /var/www
cd lapor-pak
cd lapor-pak
cd LaporPak
source venv/bin/activate
pip install gunicorn
gunicorn --bind 0.0.0.0:8000 app:app
sudo lsof -i :8000
sudo kill -9 80305 80306 80307 80308
sudo lsof -i :8000
sudo pkill gunicorn
sudo lsof -i :8000
gunicorn --bind 0.0.0.0:8000 app:app
(venv) root@gen4:/var/www/LaporPak# gunicorn --bind 0.0.0.0:8000 app:app
[2025-12-27 11:06:31 +0700] [132503] [INFO] Starting gunicorn 23.0.0
[2025-12-27 11:06:31 +0700] [132503] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-12-27 11:06:31 +0700] [132503] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-12-27 11:06:32 +0700] [132503] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-12-27 11:06:32 +0700] [132503] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-12-27 11:06:33 +0700] [132503] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-12-27 11:06:33 +0700] [132503] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-12-27 11:06:34 +0700] [132503] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-12-27 11:06:34 +0700] [132503] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-12-27 11:06:35 +0700] [132503] [ERROR] Connection in use: ('0.0.0.0', 8000)
[2025-12-27 11:06:35 +0700] [132503] [ERROR] connection to ('0.0.0.0', 8000) failed: [Errno 98] Address already in use
[2025-12-27 11:06:36 +0700] [132503] [ERROR] Can't connect to ('0.0.0.0', 8000)sudo lsof -i :8000
cd lapor_pak
pip install flask flask-sqlalchemy pymysql flask-login
ls
mkdir lapor_pak
cd lapor_pak
sudo apt update
sudo apt install python3-venv -y
python3 -m venv venv
source venv/bin/activate
pip install flask flask-sqlalchemy pymysql flask-login gunicorn
python3 app.py
ls
python3 app.py
gunicorn --bind 0.0.0.0:80 app:app
sudo systemctl stop apache2
sudo mysql
sudo apt update && sudo apt upgrade -y
sudo apt install python3-pip python3-venv mysql-server -y
cd Lapor_pak
python3 -m venv venv
source venv/bin/activate
pip install flask flask-sqlalchemy pymysql flask-login gunicorn
sudo systemctl status mysql
source venv/bin/activate
pip install pymysql cryptography
sudo ufw allow 5000
sudo ufw allow 80
nohup venv/bin/gunicorn --bind 0.0.0.0:5000 app:app &
-- Masuk ke MySQL lalu jalankan:
USE lapor_pak;
UPDATE user SET password = 'pbkdf2:sha256:260000$tY...' WHERE username = 'admin';
-- Masuk ke MySQL lalu jalankan:
USE lapor_pak;
UPDATE user SET password = 'pbkdf2:sha256:260000$tY...' WHERE username = 'admin';
USE lapor_pak;
UPDATE user SET password = 'pbkdf2:sha256:260000$tY...' WHERE username = 'admin';
sudo mysql -u root
python3 app.py
sudo snap install android-studio --classic
sudo snap install android-studio --classic
sudo snap install android-studio --classic
sudo apt install nodejs npm
platforms/android/app/build/outputs/apk/
cd NamaProject
./gradlew assembleDebug
sudo ss -lntu
cd ../opt/fadli-app-security
source venv/bin/activate
gunicorn -w 2 --bind 0.0.0.0:7000 app:app
cd /var/www
git clone https://github.com/akaaii6555-sys/akai.git
git clone -b main https://github.com/akaaii6555-sys/akai.git
exit
cd ../
cd /opt
ls
ls
exit
cd ../
cd /opt
ls
cd /akai-app-security
cd /akai-app-security
cd /satrio-app-security
cd ../
cd /opt/akai-app-security
git pull origin main
git clone https://github.com/akaaii6555-sys/akai.git akai-app-security
git pull origin main
ls
cd ../
cd /opt/akai-app-security
git pull origin main
git status
python3 -m venv .venv
source .venv/bin/activate
which python
pip install --upgrade pip
pip install -r requirements.txt
exit
